In [1]:
#Librairies
import pandas as pd
import numpy as np
import sklearn
from pretraitement import Pretraitement
from sklearn.preprocessing import LabelEncoder

In [2]:
df_test = pd.read_csv('../leaf-classification/test.csv')
df_train= pd.read_csv('../leaf-classification/train.csv')
df_test.head(5) 

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2   9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836   0.000000   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000   0.000000   0.006836   0.001953   
2      0.0  0.011719  ...   0.128910   0.000000   0.000977   0.000000   
3      0.0  0.003906  ...   0.012695   0.015625   0.002930   0.036133   
4      0.0  0.005859  ...   0.000000   0.042969   0.016602   0.010742   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 193 columns]

In [3]:
from pretraitement import Pretraitement

#test prétraitement avec PCA 
#on garde les colonnes  tel que la somme du ratio des variances soit supérieure au s
pretrait=Pretraitement(df_train)
pretrait.selection_avec_PCA(0.9)
pretrait=Pretraitement(df_train)
pretrait.selection_avec_PCA(0.95)
pretrait=Pretraitement(df_train)
pretrait.selection_avec_PCA(0.99)



pca variance ratio:  0.9045005231208898
nmb de colonne :  33
pca variance ratio:  0.9504847637817468
nmb de colonne :  49
pca variance ratio:  0.990500657703204
nmb de colonne :  89


In [4]:

# préparation des données
x_train=df_train.drop(["species","id"], axis=1)
x_etiquette=df_train["species"]


from combinaison_de_nos_modeles import Combinaisons

# application du modèle :
model_reseaux_neuronnes=Combinaisons(x_train,x_etiquette,False,df_test.drop("id",axis=1),True)
model_reseaux_neuronnes.entrainement()
kaggle_probas=model_reseaux_neuronnes.prediction(True)

#model_foret_alea.resultats()
print(kaggle_probas)


[[0.00696971 0.00993637 0.00845303 ... 0.00697018 0.00924414 0.00697014]
 [0.00845303 0.00697046 0.01253222 ... 0.0166763  0.0069697  0.01042081]
 [0.00756311 1.69036841 0.0069697  ... 0.0069697  0.0080822  0.00993679]
 ...
 [0.00771325 0.01364492 0.00696973 ... 0.00697074 0.0069697  0.00758688]
 [0.00845303 0.0069697  0.01611945 ... 0.02976717 0.0069697  0.00746453]
 [0.0069697  0.00820581 0.00696976 ... 0.00726636 0.00845303 0.01554831]]


C:\Users\Gaétan\.conda\envs\pythonProject\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [5]:

print(x_train.shape)
print(x_etiquette.shape)
print(kaggle_probas.shape)

(990, 192)
(990,)
(594, 99)


In [6]:
test_ids = df_test.id
test_data = df_test.drop(['id'], axis =1)

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_fit = encoder.fit(df_train['species'])
print(y_fit)
classes = list(y_fit.classes_) 

LabelEncoder()


In [8]:
kaggle_submission=pd.DataFrame(kaggle_probas, columns=classes)
kaggle_submission.insert(0, 'id', test_ids)
print(kaggle_submission)
#kaggle_submission.reset_index()



       id  Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  \
0       4         0.006970         0.009936   0.008453     0.013636   
1       7         0.008453         0.006970   0.012532     0.039238   
2       9         0.007563         1.690368   0.006970     0.008082   
3      12         0.013744         0.017497   0.007711     0.044081   
4      13         0.041729         0.022001   0.006970     0.007711   
..    ...              ...              ...        ...          ...   
589  1576         0.009790         1.761525   0.007464     0.008082   
590  1577         0.033300         0.017731   0.006970     0.008870   
591  1579         0.007713         0.013645   0.006970     0.006970   
592  1580         0.008453         0.006970   0.016119     0.029815   
593  1583         0.006970         0.008206   0.006970     0.009491   

     Acer_Palmatum  Acer_Pictum  Acer_Platanoids  Acer_Rubrum  Acer_Rufinerve  \
0         0.006970     0.012952         0.006974     0.006970     

In [9]:
#compression_opts = dict(method='zip',archive_name='out.csv')  
#kaggle_submission.to_csv('out.zip', index=False,compression=compression_opts)  
kaggle_submission.to_csv('result.csv',index = False)
#print(type(kaggle_submission))

In [10]:
#Merci oh seigneur stack overflow
import base64
import pandas as pd
from IPython.display import HTML

def create_download_link( df, title = "Download CSV file", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download="{filename}" href="data:text/csv;base64,{payload}" target="_blank">{title}</a>'
    html = html.format(payload=payload,title=title,filename=filename)
    return HTML(html)

create_download_link(kaggle_submission)

In [11]:
kaggle_probas = pd.DataFrame(kaggle, columns=output)
kaggle_probas.insert(0, 'id', test["id"])
kaggle_probas.to_csv(path_or_buf="submission.csv",header=True)

NameError: name 'kaggle' is not defined